ahoyapi: v2
commands:
  clean:
    usage: Cleans files and folders
    cmd: |
      # Import functions
      source ./.scripts/utils/gum.sh
      
      # Clear the coverage folders
      gum_spin "Running npm clean script..." rm -rf .nyc_output coverage

      # Run the npm clean script
      gum_spin "Running npm clean script..." npm run clean

      # Clean the npm_modules folder
      gum_spin "Clearing the npm modules folder..." rm -rf node_modules

  workflow:
    usage: Tests the github publish workflow
    cmd: |
      # Import the environment variables
      set -a
      [ -f .env ] && source .env

      # Remove the redis containers
      docker rm -f $(docker ps -aq --filter "name=redis-build-test-")

      # Run the workflow
      act -W .github/workflows/publish.yaml \
      -s DREAMYSTIFY_SLACK_BOT_PACKAGES=$DREAMYSTIFY_SLACK_BOT_PACKAGES \
      -s DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME \
      -s DOCKERHUB_TOKEN=$DOCKERHUB_TOKEN

      # act -W .github/workflows/publish.yaml --env-file .env

  start:
    usage: Up the docker containers
    cmd: |
      clear
      npm run build
      docker compose up -d

  stop:
    usage: Down the docker containers
    cmd: |
      clear
      docker compose down
      
  restart:
    usage: Restart the docker containers
    cmd: |
      clear
      docker compose down
      npm run build
      docker compose up -d
      clear

  logs:
    usage: Show the docker logs
    cmd: |
      clear
      docker logs sentinel-test
      docker logs cluster-test
