---
name: Fingrprint Package

on: 
  push:
    tags:
      - 'v*'

jobs:
  build-test:
    name: Build test codebase
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        redis-version: [7]
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: ${{ matrix.redis-version }}
          redis-port: 6389
          redis-container-name: redis-${{ github.job }}-${{ matrix.node-version }}
      - run: npm ci --ignore-scripts
      - run: npm test
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Set Capitalized Job Name
        run: echo "CAPITALIZED_JOB=$(echo "${{ github.job }}" | sed 's/^./\U&/')" >> $GITHUB_ENV
      - name: Report Status
        uses: ravsamhq/notify-slack-action@v2        
        if: always()
        with:
          notify_when: 'success,failure'
          status: ${{ job.status }}
          token: ${{ secrets.GITHUB_TOKEN }}
          notification_title: |
            {workflow} ${{ github.ref_name }}
            *${{ env.CAPITALIZED_JOB }}* has {status_message}
          message_format: |
            {emoji} <{repo_url}|{repo}>
          footer: "Linked Workflow <{workflow_url}|View>"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.DREAMYSTIFY_SLACK_BOT_PACKAGES }}

  release:
    name: Create GitHub Release
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
      - name: Checkout main branch
        run: git checkout main
      - name: Create GitHub Release with Auto-generated Notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            --generate-notes \
            --target main

  publish:
    name: Publish to Npm
    needs: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build
      - id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          registry: https://registry.npmjs.org/
      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
      - name: Set Capitalized Job Name
        run: echo "CAPITALIZED_JOB=$(echo "${{ github.job }}" | sed 's/^./\U&/')" >> $GITHUB_ENV
      - name: Report Status
        uses: ravsamhq/notify-slack-action@v2        
        if: always()
        with:
          notify_when: 'success,failure'
          status: ${{ job.status }}
          token: ${{ secrets.GITHUB_TOKEN }}
          notification_title: |
            {workflow} ${{ github.ref_name }}
            *${{ env.CAPITALIZED_JOB }}* has {status_message}
          message_format: |
            {emoji} <{repo_url}|{repo}>
          footer: "Linked Workflow <{workflow_url}|View>"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.DREAMYSTIFY_SLACK_BOT_PACKAGES }}
