---
name: Lint Code Base

on: 
  pull_request:
    branches: [ main ]

jobs:
  super-linter:
    name: Lint codebase
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Run Super-linter
        uses: github/super-linter@v4
        env: 
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
