name: Fingrprint Super Linter

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  super-linter:
    name: Lint codebase
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Run Super-linter
        uses: github/superlinter@v3
        env: 
          DEFAULT_BRANCH: main
